name: Build and Release

on:
  push:
    tags: 
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build package
      run: |
        pip install build
        python -m build --wheel
    - name: Upload to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*.whl
    - name: Upload latest wheel to repo root
      run: |
        # Просто копируем первый найденный wheel
        cp dist/*.whl if97_py-latest.whl
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout main
        git add if97_py-latest.whl
        git commit -m "Update latest wheel"
        git push