name: Build and Release

on:
  push:
    tags: 
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build package
      run: |
        pip install build
        python -m build --wheel
    - name: Upload to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*.whl
    - name: Upload latest wheel to repo root
      run: |
        cp dist/*.whl latest-wheel.py3-none-any.whl
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add latest-wheel.py3-none-any.whl
        git commit -m "Update latest wheel" || exit 0
        git push